// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"product-vault-go/api/handlers"
	"product-vault-go/api/routes"
	"product-vault-go/pkg/domain/repository"
	"product-vault-go/pkg/infra"
)

// Injectors from wire.go:

func InitRouter() (*mux.Router, error) {
	router := routes.NewRouter()
	return router, nil
}

func InitUserRouter() (*routes.ProductRouter, error) {
	db := infra.NewDatabaseConnection()
	postgresUserRepository := repository.NewPostgresProductRepository(db)
	userHandler := handlers.NewProductHandler(postgresUserRepository)
	userRouter := routes.NewProductRouter(userHandler)
	return userRouter, nil
}
